import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const sharedSource = name => path.join(scriptDir, "..", "..", "shared", name);
const windowsRenderer = name => path.join(scriptDir, "..", "..", "offline-windows", "src", "renderer", name);

// Shared UMD modules the Android renderer loads, in the same dependency order
// as the offline Windows app. style.css carries the offline profile/programme
// layout that shared/ui.css does not define; it is sourced from the Windows
// renderer so both apps share one maintained stylesheet.
const FILES = [
  "gpaCore.js",
  "dataValidation.js",
  "identityText.js",
  "programmeCatalog.js",
  "offlineProfiles.js",
  "report.js",
  "report.css",
  "ui.css"
];

async function main() {
  const target = path.join(scriptDir, "..", "src", "shared");
  await mkdir(target, { recursive: true });
  for (const name of FILES) {
    await copyFile(sharedSource(name), path.join(target, name));
  }
  // Reuse the Windows renderer stylesheet so the offline layout matches.
  await copyFile(windowsRenderer("style.css"), path.join(target, "style.css"));

  // The page CSP keeps connect-src 'none', so the programme catalogue cannot
  // be fetched or read via Filesystem. Convert the JSON into a classic script
  // that assigns the data to a global, loaded with script-src 'self'.
  const programmesJson = await readFile(sharedSource("utemPrograms.json"), "utf8");
  const dataModule = `// Generated by scripts/copy-shared.js from shared/utemPrograms.json.\n// Bundled as a local script because connect-src 'none' forbids fetching JSON.\nglobalThis.UTEM_PROGRAMMES_DATA = ${programmesJson};\n`;
  await writeFile(path.join(target, "utemProgramsData.js"), dataModule, "utf8");

  console.log(`Copied ${FILES.length} shared files, style.css, and generated utemProgramsData.js (programme catalogue) into the Android app.`);
}

main().catch(error => { console.error(error); process.exitCode = 1; });
